require_relative "core/match.rb"
require_relative "core/match_importer.rb"
require_relative "core/prediction.rb"
require_relative "core/season_generator.rb"
require_relative "core/team.rb"
require_relative "evaluation/kicktipp.rb"
require_relative "prediction_factory/previous_match.rb"